server.port=8888
spring.application.name=config-server

spring.profiles.active=local
spring.profiles.include=native

spring.cloud.config.server.native.search-locations=classpath:/config

spring.cloud.compatibility-verifier.enabled=false
management.endpoints.web.exposure.include=*

eureka.instance.hostname=${EUREKA_HOSTNAME:config-server}
eureka.client.service-url.defaultZone=${EUREKA_URI:http://discovery-server:8761/eureka/}
