# Config Server bypass
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.config.import=optional:configserver:http://localhost:8762

server.port=8766
spring.application.name=user-service

# 1. Database - Docker Port: 5434
spring.datasource.url=jdbc:postgresql://localhost:5434/user_db
spring.datasource.username=postgres
spring.datasource.password=123

# Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 2. Keycloak and JWT Settings - Docker Port: 8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/microservice-realm

# Required JWT Placeholders
jwt.grant_type=password
jwt.scope=openid offline_access
jwt.auth_server_url=http://localhost:8081
jwt.realm=microservice-realm
jwt.client_id=user-service
# Double check this secret in Keycloak if you still get unauthorized errors
jwt.client_secret=wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8

# Token URLs
jwt.issuer_uri=http://localhost:8081/realms/microservice-realm/protocol/openid-connect/token
jwt.issuer-uri=http://localhost:8081/realms/microservice-realm/protocol/openid-connect/token

# Eureka Connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true