spring.config.import=configserver:${CONFIG_URI:http://config-server:8888}
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.max-attempts=30
spring.cloud.config.retry.multiplier=1.5

server.port=8766
spring.application.name=user-service

# 1. Database - Docker Port: 5434
spring.datasource.url=jdbc:postgresql://host.docker.internal:5434/user_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# 2. Keycloak and JWT Settings - Docker Port: 8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/microservice-realm

# Required JWT Placeholders
jwt.grant_type=password
jwt.scope=openid offline_access
jwt.auth_server_url=http://keycloak:8080
jwt.realm=microservice-realm
jwt.client_id=user-service
# Double check this secret in Keycloak if you still get unauthorized errors
jwt.client_secret=wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8

# Token URLs
jwt.issuer_uri=http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/token
jwt.issuer-uri=http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/token

# Eureka Connection
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

