# -------------------------
# Basic Settings
# -------------------------
spring.application.name=product-service
server.port=8764 

# -------------------------
# Config Server and Eureka
# -------------------------
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/microservice-realm

# -------------------------
# PostgreSQL Database Settings
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -------------------------
# Swagger API Documentation
# -------------------------
springdoc.swagger-ui.path=/swagger-ui.html