# -------------------------
# Temel Uygulama Ayarlar?
# -------------------------
spring.application.name=product-service
# Portu de?i?tirdik çünkü 8081'de muhtemelen Keycloak çal???yor
server.port=8764 

# -------------------------
# Config Server & Eureka Ba?lant?lar?
# -------------------------
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

# Spring Security'nin token'lar? do?rulamas? için Keycloak adresi
# Buradaki port 8081 ise, yukar?daki server.port mutlaka farkl? olmal?!
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/microservice-realm

# -------------------------
# PostgreSQL Database Settings
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -------------------------
# Swagger API Dokümantasyonu
# -------------------------
springdoc.swagger-ui.path=/swagger-ui.html