server.port=8762
spring.application.name=config-server

#Ortak ayarlar
# Default olarak local çalýþsýn
spring.profiles.active=local
spring.profiles.include=native

# BURASI ÇOK KR?T?K: Dosyalar bu klasörde
spring.cloud.config.server.native.search-locations=classpath:/config

spring.cloud.compatibility-verifier.enabled=false
management.endpoints.web.exposure.include=*

# Eureka hostname yine sabit kalabilir
eureka.instance.hostname=config-server