# =========================================================
# CONFIG SERVER - api-gateway.properties (GÜNCEL HAL?)
# =========================================================
spring.application.name=api-gateway
server.port=8763

# Eureka Ba?lant?s?
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server Kendi Adresi
spring.cloud.config.uri=http://localhost:8762

# --- YEN? NES?L GATEWAY AYARLARI (WebFlux) ---
# Buradaki "server.webflux" tak?s? Spring Boot 3.5+ için ?artt?r.

# 1. Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# 2. Ürün Servisi Yönlendirmesi
spring.cloud.gateway.server.webflux.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products/**

# 3. Kullan?c? Servisi Yönlendirmesi
spring.cloud.gateway.server.webflux.routes[1].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**
