spring.application.name=payment-service
server.port=8771

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.max-attempts=30
spring.cloud.config.retry.multiplier=1.5

iyzipay.api-key=sandbox-WajA53xIGM8NheqsVtOg5ibjCzYQIG3S
iyzipay.secret-key=sandbox-zqnbQQPhMTaCcwe2AAdyTQ8VN39Q0IFF
iyzipay.base-url=https://sandbox-api.iyzipay.com

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

logging.level.com.n11bootcamp.payment_service=DEBUG
