# -------------------------------------------------
# LOCAL Profil Ayarlari
# -------------------------------------------------
spring.application.name=product-service
server.port=8764


# Database
spring.datasource.url=jdbc:postgresql://host.docker.internal:5434/product_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

