server.port=8766
spring.application.name=user-service

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.max-attempts=30
spring.cloud.config.retry.multiplier=1.5

spring.datasource.url=jdbc:postgresql://host.docker.internal:5434/user_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# JWT - Keycloak
jwt.grant_type=password
jwt.scope=openid offline_access
jwt.auth_server_url=http://keycloak:8080
jwt.realm=microservice-realm
jwt.issuer_uri=http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/token
jwt.client_id=user-service
jwt.client_secret=wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8

