server.port=8766
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5434/user_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT - Keycloak
jwt.grant_type=password
jwt.scope=openid offline_access
jwt.issuer_uri=http://localhost:8081/realms/microservice-realm/protocol/openid-connect/token
jwt.client_id=user-service
jwt.client_secret=wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8

spring.cloud.config.enabled=false