# =========================================================
# CONFIG SERVER - api-gateway.properties (G?NCEL HAL?)
# =========================================================
spring.application.name=api-gateway
server.port=8763

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server Kendi Adresi
spring.cloud.config.uri=http://config-server:8888

# 1. Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

spring.cloud.gateway.server.webflux.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://product-service:8764
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products,/api/products/**

spring.cloud.gateway.server.webflux.routes[1].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://user-service:8766
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**

spring.cloud.gateway.server.webflux.routes[2].id=SHOPPING-CART-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://shopping-card-service:8765
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/shopping-cart/**,/api/shopping-cart

# Yeni Versiyon Gateway Konfig�rasyonlar?
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedorigins=http://localhost:5173,http://92.249.61.16
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedmethods=GET, POST, PUT, DELETE, OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedheaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowcredentials=true

spring.cloud.gateway.server.webflux.routes[3].id=STOCK-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=http://stock-service:8769
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/stocks/**


spring.cloud.gateway.server.webflux.routes[4].id=ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=http://order-service:8770
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/orders/**,/api/orders

spring.cloud.gateway.server.webflux.routes[5].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=http://payment-service:8771
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payments/**,/api/payments



spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/microservice-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/certs
# --- Swagger Aggregation Routes ---
spring.cloud.gateway.server.webflux.routes[6].id=PRODUCT-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[6].uri=http://product-service:8764
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/v3/api-docs/product-service
spring.cloud.gateway.server.webflux.routes[6].filters[0]=RewritePath=/v3/api-docs/product-service,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[7].id=ORDER-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[7].uri=http://order-service:8770
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/v3/api-docs/order-service
spring.cloud.gateway.server.webflux.routes[7].filters[0]=RewritePath=/v3/api-docs/order-service,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[8].id=STOCK-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[8].uri=http://stock-service:8769
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/v3/api-docs/stock-service
spring.cloud.gateway.server.webflux.routes[8].filters[0]=RewritePath=/v3/api-docs/stock-service,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[9].id=SHOPPING-CART-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[9].uri=http://shopping-card-service:8765
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/v3/api-docs/shopping-cart-service
spring.cloud.gateway.server.webflux.routes[9].filters[0]=RewritePath=/v3/api-docs/shopping-cart-service,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[10].id=USER-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[10].uri=http://user-service:8766
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/v3/api-docs/user-service
spring.cloud.gateway.server.webflux.routes[10].filters[0]=RewritePath=/v3/api-docs/user-service,/v3/api-docs


spring.cloud.gateway.server.webflux.routes[11].id=PAYMENT-SERVICE-DOCS
spring.cloud.gateway.server.webflux.routes[11].uri=http://payment-service:8771
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/v3/api-docs/payment-service
spring.cloud.gateway.server.webflux.routes[11].filters[0]=RewritePath=/v3/api-docs/payment-service,/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/product-service
springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/order-service
springdoc.swagger-ui.urls[2].name=Stock Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/stock-service
springdoc.swagger-ui.urls[3].name=Shopping Cart Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/shopping-cart-service
springdoc.swagger-ui.urls[4].name=Payment Service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/payment-service
springdoc.swagger-ui.urls[5].name=User Service
springdoc.swagger-ui.urls[5].url=/v3/api-docs/user-service

