spring.application.name=order-service
server.port=8770

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.max-attempts=30
spring.cloud.config.retry.multiplier=1.5

spring.datasource.url=jdbc:postgresql://host.docker.internal:5434/order_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

stock.rabbit.exchange=stock.events.exchange
stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested
stock.rabbit.reservedRoutingKey=order.stock.reserved
stock.rabbit.rejectedRoutingKey=order.stock.rejected
order.rabbit.stockReservedQueue=order.stock.reserved.queue
order.rabbit.stockRejectedQueue=order.stock.rejected.queue

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

logging.level.com.n11bootcamp.order_service=DEBUG

